{% set version = "2.2.0" %}

package:
  name: openjpeg
  version: {{ version }}

source:
  url: https://github.com/uclouvain/openjpeg/archive/v{{ version }}.tar.gz
  sha256: 6fddbce5a618e910e03ad00d66e7fcd09cc6ee307ce69932666d54c73b7c6e7b

build:
  number: 0
  skip: True  # [win and py36]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python  # [win]
    - cmake
    - libtiff 4.0.*
    - libpng >=1.6.28,<1.7
    - zlib 1.2.8
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]
  run:
    - libtiff 4.0.*
    - libpng >=1.6.28,<1.7
    - zlib 1.2.8
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]

test:
  files:
    - p0_01.j2k
  commands:
    - opj_dump -i p0_01.j2k
    - conda inspect linkages -p $PREFIX openjpeg  # [not win]
    - conda inspect objects -p $PREFIX openjpeg  # [osx]

about:
    home: http://www.openjpeg.org/
    license: BSD 2-clauses
    license_file: LICENSE
    summary: 'An open-source JPEG 2000 codec written in C.'

extra:
  recipe-maintainers:
    - ocefpaf
    - gillins
