{% set version = "2.1.2" %}

package:
    name: openjpeg
    version: {{ version }}

source:
    fn: v{{ version }}.tar.gz
    url: https://github.com/uclouvain/openjpeg/archive/v{{ version }}.tar.gz
    md5: 40a7bfdcc66280b3c1402a0eb1a27624

build:
    number: 1
    features:
        - vc9  # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]

requirements:
    build:
        - python  # [win]
        - cmake
        - libtiff 4.0.*
        - libpng >=1.6.23,<1.7
        - zlib 1.2.*
    run:
        - libtiff 4.0.*
        - libpng >=1.6.23,<1.7
        - zlib 1.2.*

test:
    requires:
        - python {{ environ['PY_VER'] + '*' }}  # [win]
    files:
        - p0_01.j2k
    commands:
        - opj_dump -i p0_01.j2k
        # - conda inspect linkages -n _test openjpeg  # [linux]

about:
    home: http://www.openjpeg.org/
    license: BSD 2-clauses
    summary: 'An open-source JPEG 2000 codec written in C.'

extra:
  recipe-maintainers:
    - ocefpaf
    - gillins
