{% set version = "2.2.0" %}

package:
  name: openjpeg
  version: {{ version }}

source:
  url: https://github.com/uclouvain/openjpeg/archive/v{{ version }}.tar.gz
  sha256: 6fddbce5a618e910e03ad00d66e7fcd09cc6ee307ce69932666d54c73b7c6e7b

build:
  number: 2
  run_exports:
    # nothing known on abi tracker, leaving at default
    - {{ pin_subpackage('openjpeg') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libtiff
    - libpng
    - zlib

test:
  files:
    - p0_01.j2k
  commands:
    - opj_dump -i p0_01.j2k
    - conda inspect linkages -p $PREFIX openjpeg  # [not win]
    - conda inspect objects -p $PREFIX openjpeg  # [osx]

about:
    home: http://www.openjpeg.org/
    license: BSD 2-clauses
    license_file: LICENSE
    summary: 'An open-source JPEG 2000 codec written in C.'

extra:
  recipe-maintainers:
    - ocefpaf
    - gillins
