{% set version = "2.3.1" %}

package:
  name: openjpeg
  version: {{ version }}

source:
  url: https://github.com/uclouvain/openjpeg/archive/v{{ version }}.tar.gz
  sha256: 63f5a4713ecafc86de51bfad89cc07bb788e9bba24ebbf0c4ca637621aadb6a9
  patches:
    - CVE-2018-7648-6d8c0c06ee32dc03ba80acd48334e98728e56cf5.patch

build:
  number: 1
  run_exports:
    # good compatibility in 2.x series, check before new release
    # http://www.openjpeg.org/abi-check/timeline/openjpeg/
    - {{ pin_subpackage('openjpeg') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - libtiff
    - libpng
    - zlib

test:
  files:
    - p0_01.j2k
  commands:
    - opj_dump -i p0_01.j2k

about:
    home: http://www.openjpeg.org/
    license: BSD 2-Clause
    license_file: LICENSE
    summary: 'An open-source JPEG 2000 codec written in C'

extra:
  recipe-maintainers:
    - gillins
    - mingwandroid
    - ocefpaf
