{% set version = "2.3.0" %}

package:
  name: openjpeg
  version: {{ version }}

source:
  url: https://github.com/uclouvain/openjpeg/archive/v{{ version }}.tar.gz
  sha256: 3dc787c1bb6023ba846c2a0d9b1f6e179f1cd255172bde9eb75b01f1e6c7d71a
  patches:
    - CVE-2018-7648-6d8c0c06ee32dc03ba80acd48334e98728e56cf5.patch

build:
  number: 2
  run_exports:
    # good compatibility in 2.x series, check before new release
    # http://www.openjpeg.org/abi-check/timeline/openjpeg/
    - {{ pin_subpackage('openjpeg') }}
  ignore_run_exports:
    # Needed as a transitive build-time dependency to enable PNG support but
    # is not actually required by the output binaries.
    - zlib

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - libtiff
    - libpng
    - zlib

test:
  files:
    - p0_01.j2k
  commands:
    - opj_dump -i p0_01.j2k

about:
    home: http://www.openjpeg.org/
    license: BSD 2-Clause
    license_file: LICENSE
    summary: 'An open-source JPEG 2000 codec written in C'

extra:
  recipe-maintainers:
    - gillins
    - mingwandroid
    - ocefpaf
